type Todo {
  id: String
  description: String
}

type Query {
  hello: String
  myCustomMessage(msg: String): String
  getTodo(id: String): Todo
}
type Mutation {
  addTodo(description: String!): String
}
